In [ ]:
import os
import torch
import torchaudio
from torch.utils.data import Dataset , DataLoader
import json
from transformers import ASTFeatureExtractor ,ASTForAudioClassification

In [ ]:
from huggingface_hub import login
login()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
folders = ['Layal_vs_Fery' , 'Layal_vs_Hsu' , 'Layal_vs_Martin']
files_list = []

for folder in folders :
    paths = os.listdir(os.path.join('/content/drive/MyDrive' ,'dataset', folder , 'audios'))
    full_paths = [os.path.join('/content/drive/MyDrive' , 'dataset' , folder , 'audios' , path) for path in paths ]
    files_list.extend(full_paths)

In [ ]:
files_list

['/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_259_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_444_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_185_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_481_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_370_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_74_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_296_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_148_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_37_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_111_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_407_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_333_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_222_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_993_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_868_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_629_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_794_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_555_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_942_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_831_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_979_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_674_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_683_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_666_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_757_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_720_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_982_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_905_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_592_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_518_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1894_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1922_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1014_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1958_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1148_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1041_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1049_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1185_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1259_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1072_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1884_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1928_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1966_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1079_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1102_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1876_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1111_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1222_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_2684_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_2597_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_2760_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_2669_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_4450_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_1988_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_2654_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_2605_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_4510_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_2721_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_4432_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_2743_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_4440_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_2699_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_2613_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_4494_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_4537_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_5452_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_4609_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_5484_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_4522_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_5433_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_5442_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_4589_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Fery/audios/frame_4559_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_631_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_742_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_849_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_668_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_705_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_779_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_814_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_888_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_878_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_808_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_799_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_861_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1031_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_975_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_938_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1048_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_983_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1000_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1114_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1011_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_921_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_911_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1066_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1077_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_951_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1663_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2009_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1591_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2038_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2075_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1599_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2112_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1609_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_1626_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2625_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2613_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2486_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2649_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2447_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2293_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2458_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2367_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2529_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2552_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2500_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2646_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2404_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2330_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2592_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2584_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2441_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2467_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2521_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2561_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3948_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2680_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3599_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3677_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3640_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3959_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3865_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2696_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2773_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3917_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3908_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2745_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3636_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_2729_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3897_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4732_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4740_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4661_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4758_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4012_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4819_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4873_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3988_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4049_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4769_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4836_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4805_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4705_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_3974_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4696_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Hsu/audios/frame_4686_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1223_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1371_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1437_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1186_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1466_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1428_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1408_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1297_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1334_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1101_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1415_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1138_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1260_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1455_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1149_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2010_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2132_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2190_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2021_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2159_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2202_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1506_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2029_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1494_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2239_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2008_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2098_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2071_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2088_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1971_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1569_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2150_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1532_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_1526_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2124_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2059_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2981_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3018_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3220_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2245_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3301_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3259_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3055_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2282_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3294_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2959_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3248_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3267_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_2922_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4225_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4499_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4451_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4144_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3431_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3357_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4416_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3323_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3336_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4188_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4177_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4473_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_3394_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4463_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4510_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4637_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4537_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4564_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_5905_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4572_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_5254_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_5207_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_5942_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4529_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_5164_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_5868_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_5979_no_event.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_5217_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_5197_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_5261_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_4600_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_7541_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_7458_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_6225_ball_bounced.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_6197_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_7572_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_7015_ball_hit.wav',
 '/content/drive/MyDrive/dataset/Layal_vs_Martin/audios/frame_7625_ball_bounced.wav',

In [ ]:
id2label={
        0: "ball_hit",
        1: "ball_bounced",
        2: "no_event"
    },
label2id={
        "ball_hit": 0,
        "ball_bounced": 1,
        "no_event": 2
    }

In [ ]:
feature_extractor = ASTFeatureExtractor.from_pretrained(
    "MIT/ast-finetuned-audioset-10-10-0.4593"
)

In [ ]:
import torch
import torchaudio
from torch.utils.data import Dataset


class AudioDataset(Dataset):

    def __init__(self, file_paths):
        self.file_paths = file_paths

    def __len__(self):
        return len(self.file_paths)

    def __getitem__(self, idx):

        path = self.file_paths[idx]

        filename = path.split("/")[-1].split(".")[0]

        # frame_7718_ball_bounced -> ball_bounced
        label = "_".join(filename.split("_")[-2:])
        label = label2id[label]

        waveform, sr = torchaudio.load(path)

        # stereo -> mono
        if waveform.shape[0] > 1:
            waveform = waveform.mean(dim=0)

        else:
            waveform = waveform.squeeze(0)

        return {
            "waveform": waveform,
            "sampling_rate": sr,
            "labels": label
        }

In [ ]:
from sklearn.model_selection import train_test_split

train_paths, val_paths = train_test_split(
    files_list,
    test_size=0.2,
    shuffle=True,
    random_state=42
)

In [ ]:
train_dataset = AudioDataset(train_paths)
val_dataset = AudioDataset(val_paths)

In [ ]:
from torch.nn.utils.rnn import pad_sequence

import torchaudio
import torch


class ASTDataCollator:

    def __init__(self, feature_extractor):
        self.feature_extractor = feature_extractor

    def __call__(self, batch):

        waveforms = []
        labels = []

        for sample in batch:

            waveform = sample["waveform"]
            sr = sample["sampling_rate"]

            # AST expects 16 kHz
            if sr != 16000:

                waveform = torchaudio.functional.resample(
                    waveform,
                    sr,
                    16000
                )

            waveforms.append(waveform.numpy())
            labels.append(sample["labels"])

        features = self.feature_extractor(
            waveforms,
            sampling_rate=16000,
            return_tensors="pt",
            padding=True
        )

        features["labels"] = torch.tensor(labels)

        return features

In [ ]:
from transformers import ASTForAudioClassification

id2label = {
    0: "ball_hit",
    1: "ball_bounced",
    2: "no_event"
}

model = ASTForAudioClassification.from_pretrained(
    "MIT/ast-finetuned-audioset-10-10-0.4593",
    num_labels=3,
    label2id=label2id,
    id2label=id2label,
    ignore_mismatched_sizes=True)

[transformers] You passed `num_labels=3` which is incompatible to the `id2label` map of length `527`.

Loading weights:   0%|          | 0/203 [00:00<?, ?it/s]

[transformers] ASTForAudioClassification LOAD REPORT from: MIT/ast-finetuned-audioset-10-10-0.4593
Key                     | Status   |
------------------------+----------+-----------------------------------------------------------------------------------------
classifier.dense.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([527]) vs model:torch.Size([3])
classifier.dense.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([527, 768]) vs model:torch.Size([3, 768])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

In [ ]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.8.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.29.7)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.14.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.1 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
import numpy as np
import evaluate

accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")


def compute_metrics(eval_pred):

    predictions = np.argmax(
        eval_pred.predictions,
        axis=1
    )

    acc = accuracy.compute(
        predictions=predictions,
        references=eval_pred.label_ids
    )

    f1_score = f1.compute(
        predictions=predictions,
        references=eval_pred.label_ids,
        average="macro"
    )

    return {
        "accuracy": acc["accuracy"],
        "f1": f1_score["f1"]
    }

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(

    output_dir="./ast-tennis",

    num_train_epochs=15,

    learning_rate=1e-5,

    per_device_train_batch_size=16,

    per_device_eval_batch_size=16,

    eval_strategy="epoch",

    save_strategy="epoch",

    logging_steps=20,

    load_best_model_at_end=True,

    metric_for_best_model="f1",

    greater_is_better=True,

    fp16=torch.cuda.is_available(),

    save_total_limit=2,

    report_to="none",

    remove_unused_columns=False # Added this line to prevent removal of 'waveform'
)

In [ ]:
from transformers import Trainer

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=val_dataset,

    data_collator=ASTDataCollator(feature_extractor),

    processing_class=feature_extractor,

    compute_metrics=compute_metrics,
)

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['audio_spectrogram_transformer.layers.0.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.0.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.0.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.0.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.0.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.0.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.0.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.0.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.0.layernorm_before.weight', 'audio_spectrogram_transformer.layers.0.layernorm_before.bias', 'audio_spectrogram_transformer.layers.0.layernorm_after.weight', 'audio_spectrogram_transformer.layers.0.layernorm_after.bias', 'audio_spectrogram_transformer.layers.0.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.0.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.0.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.0.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.1.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.1.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.1.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.1.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.1.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.1.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.1.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.1.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.1.layernorm_before.weight', 'audio_spectrogram_transformer.layers.1.layernorm_before.bias', 'audio_spectrogram_transformer.layers.1.layernorm_after.weight', 'audio_spectrogram_transformer.layers.1.layernorm_after.bias', 'audio_spectrogram_transformer.layers.1.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.1.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.1.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.1.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.2.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.2.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.2.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.2.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.2.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.2.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.2.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.2.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.2.layernorm_before.weight', 'audio_spectrogram_transformer.layers.2.layernorm_before.bias', 'audio_spectrogram_transformer.layers.2.layernorm_after.weight', 'audio_spectrogram_transformer.layers.2.layernorm_after.bias', 'audio_spectrogram_transformer.layers.2.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.2.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.2.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.2.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.3.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.3.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.3.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.3.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.3.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.3.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.3.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.3.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.3.layernorm_before.weight', 'audio_spectrogram_transformer.layers.3.layernorm_before.bias', 'audio_spectrogram_transformer.layers.3.layernorm_after.weight', 'audio_spectrogram_transformer.layers.3.layernorm_after.bias', 'audio_spectrogram_transformer.layers.3.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.3.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.3.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.3.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.4.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.4.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.4.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.4.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.4.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.4.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.4.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.4.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.4.layernorm_before.weight', 'audio_spectrogram_transformer.layers.4.layernorm_before.bias', 'audio_spectrogram_transformer.layers.4.layernorm_after.weight', 'audio_spectrogram_transformer.layers.4.layernorm_after.bias', 'audio_spectrogram_transformer.layers.4.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.4.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.4.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.4.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.5.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.5.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.5.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.5.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.5.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.5.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.5.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.5.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.5.layernorm_before.weight', 'audio_spectrogram_transformer.layers.5.layernorm_before.bias', 'audio_spectrogram_transformer.layers.5.layernorm_after.weight', 'audio_spectrogram_transformer.layers.5.layernorm_after.bias', 'audio_spectrogram_transformer.layers.5.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.5.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.5.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.5.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.6.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.6.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.6.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.6.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.6.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.6.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.6.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.6.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.6.layernorm_before.weight', 'audio_spectrogram_transformer.layers.6.layernorm_before.bias', 'audio_spectrogram_transformer.layers.6.layernorm_after.weight', 'audio_spectrogram_transformer.layers.6.layernorm_after.bias', 'audio_spectrogram_transformer.layers.6.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.6.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.6.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.6.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.7.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.7.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.7.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.7.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.7.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.7.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.7.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.7.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.7.layernorm_before.weight', 'audio_spectrogram_transformer.layers.7.layernorm_before.bias', 'audio_spectrogram_transformer.layers.7.layernorm_after.weight', 'audio_spectrogram_transformer.layers.7.layernorm_after.bias', 'audio_spectrogram_transformer.layers.7.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.7.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.7.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.7.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.8.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.8.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.8.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.8.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.8.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.8.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.8.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.8.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.8.layernorm_before.weight', 'audio_spectrogram_transformer.layers.8.layernorm_before.bias', 'audio_spectrogram_transformer.layers.8.layernorm_after.weight', 'audio_spectrogram_transformer.layers.8.layernorm_after.bias', 'audio_spectrogram_transformer.layers.8.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.8.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.8.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.8.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.9.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.9.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.9.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.9.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.9.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.9.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.9.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.9.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.9.layernorm_before.weight', 'audio_spectrogram_transformer.layers.9.layernorm_before.bias', 'audio_spectrogram_transformer.layers.9.layernorm_after.weight', 'audio_spectrogram_transformer.layers.9.layernorm_after.bias', 'audio_spectrogram_transformer.layers.9.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.9.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.9.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.9.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.10.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.10.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.10.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.10.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.10.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.10.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.10.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.10.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.10.layernorm_before.weight', 'audio_spectrogram_transformer.layers.10.layernorm_before.bias', 'audio_spectrogram_transformer.layers.10.layernorm_after.weight', 'audio_spectrogram_transformer.layers.10.layernorm_after.bias', 'audio_spectrogram_transformer.layers.10.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.10.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.10.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.10.mlp.fc2.bias', 'audio_spectrogram_transformer.layers.11.attention.q_proj.weight', 'audio_spectrogram_transformer.layers.11.attention.q_proj.bias', 'audio_spectrogram_transformer.layers.11.attention.k_proj.weight', 'audio_spectrogram_transformer.layers.11.attention.k_proj.bias', 'audio_spectrogram_transformer.layers.11.attention.v_proj.weight', 'audio_spectrogram_transformer.layers.11.attention.v_proj.bias', 'audio_spectrogram_transformer.layers.11.attention.o_proj.weight', 'audio_spectrogram_transformer.layers.11.attention.o_proj.bias', 'audio_spectrogram_transformer.layers.11.layernorm_before.weight', 'audio_spectrogram_transformer.layers.11.layernorm_before.bias', 'audio_spectrogram_transformer.layers.11.layernorm_after.weight', 'audio_spectrogram_transformer.layers.11.layernorm_after.bias', 'audio_spectrogram_transformer.layers.11.mlp.fc1.weight', 'audio_spectrogram_transformer.layers.11.mlp.fc1.bias', 'audio_spectrogram_transformer.layers.11.mlp.fc2.weight', 'audio_spectrogram_transformer.layers.11.mlp.fc2.bias'].

TrainOutput(global_step=225, training_loss=0.11437210517521534, metrics={'train_runtime': 670.3523, 'train_samples_per_second': 5.147, 'train_steps_per_second': 0.336, 'total_flos': 2.338528840777728e+17, 'train_loss': 0.11437210517521534, 'epoch': 15.0})

In [ ]:
pip install huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.23.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)

In [ ]:
from huggingface_hub import login
login()

In [ ]:
trainer.push_to_hub()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

CommitInfo(commit_url='https://huggingface.co/ahmedmohamed55/ast-tennis/commit/77f53c8443162e0d882c5d410c155469df96f37e', commit_message='End of training', commit_description='', oid='77f53c8443162e0d882c5d410c155469df96f37e', pr_url=None, repo_url=RepoUrl('https://huggingface.co/ahmedmohamed55/ast-tennis', endpoint='https://huggingface.co', repo_type='model', repo_id='ahmedmohamed55/ast-tennis'), pr_revision=None, pr_num=None)